
image: maven:3-eclipse-temurin-22 
stages:
  - test
before_script:
  - apt-get update > /dev/null 2>&1
  - apt-get install -y wget curl > /dev/null 2>&1
  - wget -qO- https://dl.google.com/linux/linux_signing_key.pub | tee /usr/share/keyrings/google-chrome.asc > /dev/null 2>&1
  - echo "deb [signed-by=/usr/share/keyrings/google-chrome.asc] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list > /dev/null 2>&1
  - apt-get update > /dev/null 2>&1
  - apt-get install -y google-chrome-stable > /dev/null 2>&1
  - echo "$STAG_ENV_CONFIGS" > src/main/resources/config.properties
selenium-test-job:
  stage: test
  parallel:
    matrix:
      - TEST_CONFIG_PATH: 
          - test_configs/smoke/web/seller/DashboardLoginTest.xml
          - test_configs/smoke/web/seller/DashboardSupplierTest.xml
          - test_configs/smoke/web/seller/DashboardCreateProductTest.xml
          - test_configs/smoke/web/seller/DashboardUpdateProductTest.xml
          - test_configs/smoke/web/seller/DashboardProductManagementTest.xml
  script:
    - mvn install -DskipTests > /dev/null 2>&1
    - mvn test "-DsuiteFile=test_configs/$TEST_TYPE/web/seller/$TEST_CONFIG_PATH"
  artifacts:
    paths:
      - target/ExtentReport.html
      - target/BufferLog.log
    when: always