
image: maven:3-eclipse-temurin-22 
stages:
  - test
before_script:
  - apt-get update > /dev/null 2>&1
  - apt-get install -y wget curl > /dev/null 2>&1
  - wget -qO- https://dl.google.com/linux/linux_signing_key.pub | tee /usr/share/keyrings/google-chrome.asc > /dev/null 2>&1
  - echo "deb [signed-by=/usr/share/keyrings/google-chrome.asc] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list > /dev/null 2>&1
  - apt-get update > /dev/null 2>&1
  - apt-get install -y google-chrome-stable > /dev/null 2>&1
  - echo "$STAG_ENV_CONFIGS" > src/main/resources/config.properties
selenium-test-job:
  stage: test
  script:
    - mvn install -DskipTests > /dev/null 2>&1
    - mvn test "-DsuiteFile=test_configs/smoke/web/seller/DashboardLoginTest.xml"
  artifacts:
    paths:
      - target/ExtentReport.html
      - target/BufferLog.log
    when: always
  # when: manual  # Allows manual execution
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "push"'
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  #   - if: '$CI_PIPELINE_SOURCE == "schedule"'
  #   - if: '$CI_PIPELINE_SOURCE == "web"'  
  #     when: manual  # Enables manual trigger in the UI