name: Run Android Test with Docker image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the target environment"
        required: true
        type: choice
        options:
          - CA2 VN
          - CA2 BIZ
          - CA VN
          - CA BIZ
          - Staging VN
          - Staging BIZ
          - Production VN
          - Production BIZ
        default: "Staging VN"
      testType:
        description: "Select the test type"
        required: true
        type: choice
        options:
          - Smoke Test
          - Regression Test
        default: "Smoke Test"
      test_configs:
        description: >
          List of test configurations (JSON format). 
          Example: 
          [
            "AndroidGoSELLERCreateProductTest.xml",
            "AndroidGoSELLERUpdateProductTest.xml",
            "AndroidGoSELLERProductManagement.xml",
            "AndroidGoSELLERSupplierTest.xml",
            "AndroidGoBuyerProductDetail.xml"
          ]
        required: true
        type: string
        default: '[]'

run-name: "[${{ github.event.inputs.environment }}][${{ github.event.inputs.testType }}] Run android test with Docker image ${{ github.event.inputs.test_configs }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}-${{ github.event.inputs.testType }}-${{ github.event.inputs.test_configs }}
  cancel-in-progress: true

jobs:
  JOB:
    env:
      TEST_TYPE: ${{ github.event.inputs.testType == 'Smoke Test' && 'smoke' || 'regression' }}
    strategy:
      fail-fast: false
      matrix:
        xmlConfiguration: ${{ fromJson(inputs.test_configs) }}

    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Set User Type
        run: |
          test_name=$(basename "${{ matrix.xmlConfiguration }}" .xml)
          echo "test_name=$test_name" >> $GITHUB_ENV
          if echo "$test_name" | grep -qE "SELLER"; then
            user_type="seller"
          else
            user_type="buyer"
          fi
          echo "user_type=$user_type" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load Cached Docker Image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Pull Docker Image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          docker pull thangnguyen0495/android-appium:latest
          mkdir -p ${{ github.workspace }}/.docker-cache
          docker save -o ${{ github.workspace }}/.docker-cache/android-appium.tar thangnguyen0495/android-appium:latest

      - name: Load Cached Docker Image
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: docker load -i ${{ github.workspace }}/.docker-cache/android-appium.tar

      - name: Start Docker Container
        run: |
          docker run -d --name emulator-container --privileged \
            thangnguyen0495/android-appium:latest

      - name: Wait for Emulator to Start
        run: |
          docker logs emulator-container

      - name: Run Maven inside Docker with JDK 22
        run: |
          docker cp . emulator-container:/app

          # Run Maven commands inside the container
          docker exec emulator-container bash -c "
            cd /app && \
            mvn install -DskipTests && \
            echo '${{ secrets.ENV_FILES }}' > src/main/resources/config.properties && \
            echo '${{ vars.APP_URL }}' >> src/main/resources/config.properties && \
            echo '${{ vars.REUSE_VARIABLE }}' >> src/main/resources/config.properties && \
            mvn test -DsuiteFile=src/test/resources/${{ env.TEST_TYPE }}/android/${{ env.user_type }}/${{ matrix.xmlConfiguration }}"

      - name: Copy Test Reports from Container
        if: always()
        run: docker cp emulator-container:/app/target/ExtentReport.html ./${{ env.test_name }}.html

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.test_name }}
          path: ./${{ env.test_name }}.html
