name: Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Dashboard-CreateProduct:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "API_HOST=${{ secrets.API_HOST }}" >> $GITHUB_ENV
          echo "BROWSER=${{ secrets.BROWSER }}" >> $GITHUB_ENV
          echo "DOMAIN=${{ secrets.DOMAIN }}" >> $GITHUB_ENV
          echo "SF_ENDPOINT=${{ secrets.SF_ENDPOINT }}" >> $GITHUB_ENV
          echo "BUYER_ACCOUNT=${{ secrets.BUYER_ACCOUNT }}" >> $GITHUB_ENV
          echo "BUYER_PASSWORD=${{ secrets.BUYER_PASSWORD }}" >> $GITHUB_ENV
          echo "SELLER_ACCOUNT=${{ secrets.SELLER_ACCOUNT }}" >> $GITHUB_ENV
          echo "SELLER_PASSWORD=${{ secrets.SELLER_PASSWORD }}" >> $GITHUB_ENV
          echo "HEADLESS=${{ secrets.HEADLESS }}" >> $GITHUB_ENV

      - name: Log environment variables (for debugging)
        run: printenv

      - name: Ensure generate-config.sh is executable
        run: chmod +x ./scripts/generate-config.sh

      - name: Generate config.properties
        run: ./scripts/generate-config.sh
            
      - uses: ThangNguyen0495/execute-selenium-test@v1.0.0
        with:
          test_name: "Dashboard-CreateProduct"
          scripts: |
            ./scripts/generate-config.sh
            mvn test "-DsuiteFile=test_configs/web/create_product.xml"

#  Dashboard-UpdateProduct:
#    needs: Get-SourceCode
#    runs-on: ubuntu-latest
#    steps:
#      - uses: ThangNguyen0495/execute-selenium-test@v1.0.0
#        with:
#          artifact: "ClonedRepo"
#          test_name: "Dashboard-UpdateProduct"
#          test_config: "test_config/web/dashboard/product/update_product.xml"
