name: Pipelines

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Target environment (e.g., STAG_VN)"
        required: true
        default: "STAG_VN"
jobs:
  Dashboard-Login:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_env }}  # Pass the environment dynamically
    steps:
      - name: Test new configs
#        run: |
#          echo '${{ secrets.ENV_FILES }}' > config.txt
#
#      - name: Upload Configs
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: Configsss
#          path: config.txt
        uses: ThangNguyen0495/execute-selenium-test@v1.0.0
        with:
          test_name: "Dashboard-Login"
          scripts: |
            echo '${{ secrets.ENV_FILES }}' > src/main/resources/config.properties
            mvn test "-DsuiteFile=test_configs/web/seller/loginTest.xml"


