name: Pipelines

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Target environment (e.g., STAG_VN)"
        required: true
        default: "STAG_VN"

jobs:
  dynamic-env-secret:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_env }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute test with
        env:
          ENV_FILES: ${{ secrets.ENV_FILES }}
        uses: ThangNguyen0495/execute-selenium-test@v1.0.0
        with:
            test_name: "Dashboard-CreateProduct"
            scripts: |
              echo "$ENV_FILES" >> src/main/resources/config.properties
              chmod 600 src/main/resources/config.properties
              mvn test "-DsuiteFile=test_configs/web/seller/create_product.xml"
