name: Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup-config:
    runs-on: ubuntu-latest
    steps:
      - name: Generate config.properties file
        run: |
          # Create the config file with sensitive values from GitHub Secrets
          echo "buyerAccount=${{ secrets.BUYER_ACCOUNT }}" > src/main/resources/config.properties
          echo "buyerPassword=${{ secrets.BUYER_PASSWORD }}" >> src/main/resources/config.properties
          echo "sellerAccount=${{ secrets.SELLER_ACCOUNT }}" >> src/main/resources/config.properties
          echo "sellerPassword=${{ secrets.SELLER_PASSWORD }}" >> src/main/resources/config.properties
          echo "apiHost=${{ secrets.API_HOST }}" >> src/main/resources/config.properties
          echo "browser=${{ secrets.BROWSER }}" >> src/main/resources/config.properties
          echo "domain=${{ secrets.DOMAIN }}" >> src/main/resources/config.properties
          echo "storeURL=${{ secrets.STORE_URL }}" >> src/main/resources/config.properties
          echo "headless=${{ secrets.HEADLESS }}" >> src/main/resources/config.properties
          echo "enableProxy=false" >> src/main/resources/config.properties
          chmod 600 src/main/resources/config.properties

  Dashboard-Login:
    needs: setup-config
    runs-on: ubuntu-latest
    steps:
      - name: Run Dashboard-Login Test
        uses: ThangNguyen0495/execute-selenium-test@v1.0.0
        with:
          test_name: "Dashboard-Login"
          scripts: |
            mvn test "-DsuiteFile=test_configs/web/seller/loginTest.xml"
#
#  Dashboard-CreateProduct:
#    needs: setup-config
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run Dashboard-CreateProduct Test
#        uses: ThangNguyen0495/execute-selenium-test@v1.0.0
#        with:
#          test_name: "Dashboard-CreateProduct"
#          scripts: |
#            mvn test "-DsuiteFile=test_configs/web/seller/create_product.xml"
#
#  Dashboard-UpdateProduct:
#    needs: setup-config
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run Dashboard-UpdateProduct Test
#        uses: ThangNguyen0495/execute-selenium-test@v1.0.0
#        with:
#          test_name: "Dashboard-UpdateProduct"
#          scripts: |
#            mvn test "-DsuiteFile=test_configs/web/seller/update_product.xml"
#
#  Dashboard-ProductManagement:
#    needs:
#      - Dashboard-CreateProduct
#      - Dashboard-UpdateProduct
#    runs-on: ubuntu-latest
#    if: always()
#    steps:
#      - name: Run Dashboard-ProductManagement Test
#        uses: ThangNguyen0495/execute-selenium-test@v1.0.0
#        with:
#          test_name: "Dashboard-ProductManagement"
#          scripts: |
#            mvn test "-DsuiteFile=test_configs/web/seller/product_management.xml"
#
#  Storefront-ProductDetail:
#    needs: setup-config
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run Storefront-ProductDetail Test
#        uses: ThangNguyen0495/execute-selenium-test@v1.0.0
#        with:
#          test_name: "Storefront-ProductDetail"
#          scripts: |
#            mvn test "-DsuiteFile=test_configs/web/buyer/product_detail.xml"