name: Pipeline

on:
  push:
    branches:
      - Thang-Test
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Dashboard-CreateProduct:
    runs-on: ubuntu-latest
    steps:
      - uses: ThangNguyen0495/execute-selenium-test@v1.0.0
        with:
          test_name: "Dashboard-CreateProduct"
          scripts: |
            echo "buyerAccount=${{ secrets.BUYER_ACCOUNT }}" > src/main/resources/config.properties
            echo "buyerPassword=${{ secrets.BUYER_PASSWORD }}" >> src/main/resources/config.properties
            echo "sellerAccount=${{ secrets.SELLER_ACCOUNT }}" >> src/main/resources/config.properties
            echo "sellerPassword=${{ secrets.SELLER_PASSWORD }}" >> src/main/resources/config.properties
            echo "apiHost=${{ secrets.API_HOST }}" >> src/main/resources/config.properties
            echo "browser=${{ secrets.BROWSER }}" >> src/main/resources/config.properties
            echo "domain=${{ secrets.DOMAIN }}" >> src/main/resources/config.properties
            echo "sfEndpoint=${{ secrets.SF_ENDPOINT }}" >> src/main/resources/config.properties
            echo "headless=${{ secrets.HEADLESS }}" >> src/main/resources/config.properties
            chmod 600 src/main/resources/config.properties
            mvn test "-DsuiteFile=test_configs/web/create_product.xml"
  Dashboard-UpdateProduct:
    runs-on: ubuntu-latest
    steps:
      - uses: ThangNguyen0495/execute-selenium-test@v1.0.0
        with:
          test_name: "Dashboard-UpdateProduct"
          scripts: |
            echo "buyerAccount=${{ secrets.BUYER_ACCOUNT }}" > src/main/resources/config.properties
            echo "buyerPassword=${{ secrets.BUYER_PASSWORD }}" >> src/main/resources/config.properties
            echo "sellerAccount=${{ secrets.SELLER_ACCOUNT }}" >> src/main/resources/config.properties
            echo "sellerPassword=${{ secrets.SELLER_PASSWORD }}" >> src/main/resources/config.properties
            echo "apiHost=${{ secrets.API_HOST }}" >> src/main/resources/config.properties
            echo "browser=${{ secrets.BROWSER }}" >> src/main/resources/config.properties
            echo "domain=${{ secrets.DOMAIN }}" >> src/main/resources/config.properties
            echo "sfEndpoint=${{ secrets.SF_ENDPOINT }}" >> src/main/resources/config.properties
            echo "headless=${{ secrets.HEADLESS }}" >> src/main/resources/config.properties
            chmod 600 src/main/resources/config.properties
            mvn test "-DsuiteFile=test_configs/web/update_product.xml"
