name: Pipelines

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Target environment (e.g., STAG_VN)"
        required: true
        default: "STAG_VN"

jobs:
  Dashboard-Login:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_env }}
    steps:
      - name: Test new configs
        env:
          CONFIG_FILES: ${{ secrets.ENV_FILES }}
        uses: ThangNguyen0495/execute-selenium-test@v1.0.0
        with:
          test_name: "Dashboard-Login"
          scripts: |
            echo "$CONFIG_FILES" >> src/main/resources/config.properties
            chmod 600 src/main/resources/config.properties
            mvn test "-DsuiteFile=test_configs/web/seller/loginTest.xml"
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Configs
          path: |
            **/src/main/resources/config.properties