name: Pipelines

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Target environment (e.g., STAG_VN)"
        required: true
        default: "STAG_VN"

jobs:
  Dashboard-Login:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_env }}  # Pass the environment dynamically
    steps:
      - name: Test new configs
        env:
          CONFIG_FILES: ${{ secrets.ENV_FILES }}  # Access the secret ENV_FILES
        uses: ThangNguyen0495/execute-selenium-test@v1.0.0
        with:
          test_name: "Dashboard-Login"
          scripts: |
            # Write the CONFIG_FILES content into the config.properties file
            echo "$CONFIG_FILES" >> src/main/resources/config.properties
            
            # Change file permissions to ensure it's accessible only by the user
            chmod 600 src/main/resources/config.properties
            
            # Run the Maven test
            mvn test "-DsuiteFile=test_configs/web/seller/loginTest.xml"

      - name: Upload Test Report
        if: always()  # Ensure this runs even if the previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: Configs  # Name of the artifact
          path: src/main/resources/config.properties  # Correct the path to the file
