name: Pipeline

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: "Target environment (e.g., STAG_VN)"
        required: false
        default: "STAG_VN"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
#  Dashboard-Login:
#    runs-on: ubuntu-latest
#    environment: ${{ github.event.inputs.target_env }}
#    steps:
#      - uses: ThangNguyen0495/execute-selenium-test@v1.0.0
#        with:
#          test_name: "Dashboard-Login"
#          scripts: |
#            echo '${{ secrets.ENV_FILES }}' > src/main/resources/config.properties
#            mvn test "-DsuiteFile=test_configs/web/seller/loginTest.xml"

  Dashboard-CreateProduct:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target_env }}
    steps:
      - uses: ThangNguyen0495/execute-selenium-test@v1.0.0
        with:
          test_name: "Dashboard-CreateProduct"
          scripts: |
            echo '${{ secrets.ENV_FILES }}' > src/main/resources/config.properties
            mvn test "-DsuiteFile=test_configs/web/seller/create_product.xml"
#
#  Dashboard-UpdateProduct:
#    runs-on: ubuntu-latest
#    environment: ${{ github.event.inputs.target_env }}
#    steps:
#      - uses: ThangNguyen0495/execute-selenium-test@v1.0.0
#        with:
#          test_name: "Dashboard-UpdateProduct"
#          scripts: |
#            echo '${{ secrets.ENV_FILES }}' > src/main/resources/config.properties
#            mvn test "-DsuiteFile=test_configs/web/seller/update_product.xml"
#
#  Dashboard-ProductManagement:
#    runs-on: ubuntu-latest
#    environment: ${{ github.event.inputs.target_env }}
#    needs:
#      - Dashboard-CreateProduct
#      - Dashboard-UpdateProduct
#
#    if: always()
#    steps:
#      - uses: ThangNguyen0495/execute-selenium-test@v1.0.0
#        with:
#          test_name: "Dashboard-ProductManagement"
#          scripts: |
#            echo '${{ secrets.ENV_FILES }}' > src/main/resources/config.properties
#            mvn test "-DsuiteFile=test_configs/web/seller/product_management.xml"
#
#  Storefront-ProductDetail:
#    runs-on: ubuntu-latest
#    environment: ${{ github.event.inputs.target_env }}
#    steps:
#      - uses: ThangNguyen0495/execute-selenium-test@v1.0.0
#        with:
#          test_name: "Storefront-ProductDetail"
#          scripts: |
#            echo '${{ secrets.ENV_FILES }}' > src/main/resources/config.properties
#            mvn test "-DsuiteFile=test_configs/web/buyer/product_detail.xml"


